version: "3.5"

volumes:
  mongo_data:
  mongo_config:

services:
  cve_search:
    image: cve_search
    build:
      context: .
      args:
        - REPO=cve-search/cve-search
        - BRANCH=master
        - WITH_DB=false
        - CVE_START_YEAR=2020
        - UPDATE_CRON=*/5 * * * *
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      - PYTHONUNBUFFERED=TRUE
      - WORKER_SIZE=1
    ports:
      - 8443:5000
