version: "3.5"

volumes:
  mongo_data:
  mongo_config:


services:

  cve_search_from_hub:
    image: computablefacts/cve-search:4.2.1-withdb
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - 8443:5000
