name: Build and publish Docker Hub image

on:
  push:
    branches:
      - 'master'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for image
        id: meta_std_4_2_1
        uses: docker/metadata-action@v3
        with:
          images: computablefacts/cve-search
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{version}},value=4.2.1
            type=pep440,pattern={{major}}.{{minor}},value=4.2.1
            type=sha
            type=sha,format=long

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BRANCH=v4.2.1
          push: true
          tags: ${{ steps.meta_std_4_2_1.outputs.tags }}
          labels: ${{ steps.meta_std_4_2_1.outputs.labels }}
